### PR TITLE
Make sure people install ember-fetch

### LINKED ISSUE #1: Error: Assertion Failed: Expected service:adapter to resolve to an Ember.Service but instead it was [object Object]
I seem to be getting an error trying to inject the service.

```
Error: Assertion Failed: Expected service:adapter to resolve to an Ember.Service but instead it was [object Object].
    at new EmberError (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/@ember/error/index.js:40:1)
    at assert (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/@ember/debug/index.js:132:1)
    at validateType (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/@ember/application/lib/validate-type.js:23:1)
    at Class.resolve (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/@ember/application/globals-resolver.js:142:1)
    at _resolve (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/container.js:889:1)
    at Registry.resolve (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/container.js:591:1)
    at Registry.resolve (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/container.js:595:1)
    at _has (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/container.js:906:1)
    at Registry.has (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/container.js:642:1)
    at Registry.validateInjections (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/container.js:841:1)
    at FactoryManager.create (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/container.js:407:1)
    at instantiateFactory (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/container.js:249:1)
    at _lookup (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/container.js:181:1)
    at Container.lookup (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/container.js:78:1)
    at Class.lookup (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/ember-runtime/lib/mixins/container_proxy.js:23:1)
    at UnresolvedHandlerInfoByParam.getHandler (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/ember-routing/lib/system/router.js:418:1)
    at UnresolvedHandlerInfoByParam.fetchHandler (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/router.js:575:1)
    at UnresolvedHandlerInfoByParam.get (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/router.js:734:1)
    at URLTransitionIntent.applyToState (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/router.js:1160:1)
    at Router.getTransitionByIntent (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/router.js:1473:1)
    at Router.transitionByIntent (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/router.js:1280:1)
    at doTransition (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/router.js:1908:1)
    at Router.handleURL (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/router.js:1311:1)
    at Class._doURLTransition (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/ember-routing/lib/system/router.js:258:1)
    at Class.handleURL (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/ember-routing/lib/system/router.js:255:1)
    at Class.visit (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/@ember/application/instance.js:189:1)
    at buildAppInstance.then.then (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli-fastboot/node_modules/fastboot/src/ember-app.js:260:28)
    at tryCatcher (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/rsvp.js:200:1)
    at invokeCallback (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/rsvp.js:372:1)
    at publish (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/rsvp.js:358:1)
    at /Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/ember-testing/lib/ext/rsvp.js:14:1
    at invokeWithOnError (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/backburner.js:256:1)
    at Queue.flush (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/backburner.js:167:1)
    at DeferredActionQueues.flush (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/backburner.js:326:1)
    at Backburner._end (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/backburner.js:772:1)
    at Backburner._boundAutorunEnd (/Users/rwwagner/shipshape/shipshape.io/tmp/broccoli_merge_trees-output_path-vbYM6jwK.tmp/assets/backburner.js:484:1)
    at process._tickCallback (internal/process/next_tick.js:178:7)
```

### PR DESCRIPTION
**Pull request by RobbieTheWagner**
Fixes #1

### CODE REVIEW

**Comment by tchak** [comment]
Thanks. I added a blueprint to deal with this.
https://github.com/tchak/ember-fetch-adapter/commit/085687878b2fb5af94c9a439e5c6a2d088360f53

**Comment by RobbieTheWagner** [comment]
@tchak shouldn't the blueprint use `addAddonsToProject` instead of `addPackagesToProject`?

**Comment by tchak** [comment]
Ah let me check. I just copied from another addon :)

**Comment by tchak** [comment]
done

**Pull request closed without merging**
